export const metadata = {
  title: "Catalogo de productos",
  description: "Generated by create next app",
};

import { CartProvider } from "@/context/cartContext";

export default function RootLayout({ children }) {
  return (
    <CartProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </CartProvider>
  );
}
